import { NextResponse } from "next/server";
import { getSession } from "@/lib/session";
import { getProject, mutateDB, newId, readDB } from "@/lib/store";
import { callGemini, generateDraftPlan, type EngineName } from "@/lib/llm";
import type { Draft, DraftPage, Project } from "@/lib/types";

type Params = { params: { id: string } };

export async function POST(req: Request, { params }: Params) {
  const user = await getSession();
  if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  const body = await req.json().catch(() => ({}));
  const pushToFigma = body?.pushToFigma === true;

  const db = await readDB();
  const project = getProject(db, params.id);
  if (!project) return NextResponse.json({ error: "Project not found" }, { status: 404 });

  // Stage 6: build the structural draft plan. Gemini contributes the reasoning
  // behind layout/palette/typography when configured; otherwise the heuristic
  // engine produces the same shape deterministically.
  let engine: EngineName = "desgenz-heuristic";
  let pages: DraftPage[] | null = null;
  let notes = "";

  const prompt = `You are the DesGenZ Design Draft Generator. Project "${project.name}" for client "${project.client}" (budget tier: ${project.budgetTier}). Confirmed deliverables: ${JSON.stringify(project.requirements.deliverables)}. Return JSON: { "pages": [{ "name": string, "sections": [{ "name": string, "height": number, "tone": "primary"|"accent"|"surface"|"muted" }] }], "palette": ["#hex", ...5 colors], "typography": { "heading": string, "body": string, "note": string }, "notes": "3-4 sentences of design rationale" }. Budget tier controls depth: starter=3 screens, standard=6, premium=10.`;
  const response = await callGemini(prompt);
  if (response) {
    const match = response.match(/\{[\s\S]*\}/);
    if (match) {
      try {
        const parsed = JSON.parse(match[0]);
        if (Array.isArray(parsed.pages) && parsed.pages.length) {
          pages = parsed.pages.map((p: { name: string; sections: DraftPage["sections"] }) => ({
            name: String(p.name || "Page"),
            sections: Array.isArray(p.sections) ? p.sections : [],
          }));
          engine = "gemini-2.5-flash";
          notes = String(parsed.notes || "");
        }
      } catch {
        // fall through to heuristic plan
      }
    }
  }

  const fallback = generateDraftPlan(project);
  const plan = pages ? { pages, palette: parsed_palette(response), typography: parsed_typography(response), tierPlan: fallback.tierPlan } : fallback;

  if (!pages) notes = fallbackNote(project, plan.palette, plan.typography);

  let figmaRef: string | undefined;
  let figmaNote = "";
  if (pushToFigma) {
    const mcp = await pushToFigmaMcp(project, plan);
    figmaRef = mcp.ref;
    figmaNote = mcp.message;
  }

  const now = new Date().toISOString();
  const draft: Draft = {
    id: newId("d"),
    projectId: project.id,
    version: project.drafts.length + 1,
    status: "ready",
    pages: plan.pages,
    palette: plan.palette,
    typography: plan.typography,
    notes,
    createdAt: now,
    figmaRef,
  };

  const updated = await mutateDB((db2) => {
    const p = getProject(db2, params.id)!;
    // Regeneration snapshots the previous draft as a version entry (Stage 9)
    if (p.drafts.length > 0) {
      const prev = p.drafts[p.drafts.length - 1];
      p.versions.unshift({
        id: newId("v"),
        label: `v${prev.version} — superseded`,
        note: "Replaced by a newer generated draft",
        at: now,
        draftId: prev.id,
      });
    }
    p.drafts.push(draft);
    p.stage = "review";
    p.updatedAt = now;
    return p;
  });

  return NextResponse.json({ project: updated, engine, figma: figmaNote || null });
}

// ---------- helpers ----------

interface ProjectLike {
  id: string;
  budgetTier: string;
  requirements: { deliverables: string[] };
}

function fallbackNote(project: ProjectLike, palette: string[], typography: { heading: string; body: string; note: string }): string {
  const tier = project.budgetTier;
  const screens = planScreens(project);
  return `Rough structural pass generated by the heuristic engine. ${screens} screens composed from the confirmed deliverables for a ${tier}-tier budget. Palette and type pairing chosen from the project's domain signals (${palette[2] ?? "accent"} accent, ${typography.heading || "Inter"}/${typography.body || "Inter"}). Label to client: structural first pass, not a finished design.`;
}

function planScreens(project: ProjectLike): number {
  const tierScreens: Record<string, number> = { starter: 3, standard: 6, premium: 10 };
  return tierScreens[project.budgetTier] ?? 6;
}

function parsed_palette(raw: string | null): string[] {
  if (!raw) return [];
  const m = raw.match(/"palette"\s*:\s*\[([\s\S]*?)\]/);
  if (!m) return [];
  const colors = m[1].match(/#[0-9a-fA-F]{6}/g);
  return colors ?? [];
}

function parsed_typography(raw: string | null): { heading: string; body: string; note: string } {
  if (!raw) return { heading: "", body: "", note: "" };
  const field = (name: string) => {
    const m = raw.match(new RegExp(`"${name}"\\s*:\\s*"([^"]*)"`));
    return m?.[1] ?? "";
  };
  return { heading: field("heading"), body: field("body"), note: field("note") };
}

async function pushToFigmaMcp(
  project: Project,
  plan: { pages: DraftPage[]; palette: string[]; typography: { heading: string; body: string; note: string }; tierPlan: { screens: number; sections: string[] } }
): Promise<{ ref?: string; message: string }> {
  const endpoint = process.env.FIGMA_MCP_ENDPOINT;
  const token = process.env.FIGMA_MCP_TOKEN;
  if (!endpoint || !token) {
    return {
      message: "Figma MCP not configured (set FIGMA_MCP_ENDPOINT and FIGMA_MCP_TOKEN). The structural draft is shown in-app instead.",
    };
  }
  try {
    const res = await fetch(endpoint, {
      method: "POST",
      headers: { "Content-Type": "application/json", Authorization: `Bearer ${token}` },
      body: JSON.stringify({
        name: `${project.name} — DesGenZ structural draft`,
        pages: plan.pages,
        palette: plan.palette,
        typography: plan.typography,
      }),
    });
    if (!res.ok) {
      return { message: `Figma MCP push failed (${res.status}). Draft retained in-app.` };
    }
    const data = await res.json();
    return { ref: data?.fileKey ?? data?.ref, message: "Draft pushed to Figma via MCP." };
  } catch (err) {
    console.error("Figma MCP push error", err);
    return { message: "Figma MCP unreachable. Draft retained in-app." };
  }
}
